name: i3s-backends-validator
version: 2.0.4
appVersion: 4.0.1
description: Web-based App to validate backends on Harbor
keywords:
  - backends
  - go
  - react
home: https://github.com/jp-gouin/helm-harbor-artifact-manager
icon: https://image.flaticon.com/icons/svg/1236/1236784.svg
source:
- https://github.com/jp-gouin/helm-harbor-artifact-manager
maintainers:
- name: Jean-Philippe Gouin
