apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "validator.fullname" . }}
  labels:
    app: {{ template "validator.name" . }}
    chart: {{ template "validator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
data: 
{{- with .Values.cm.script }}
{{ toYaml . | indent 2 }}
{{- end }}